CREATE TABLE "AUTH_ITEM" 
(	
	"NAME" VARCHAR2(64 BYTE) not null, 
	"TYPE" NUMBER not null, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"BIZRULE" VARCHAR2(4000 BYTE), 
	"DATA" VARCHAR2(4000 BYTE),
	CONSTRAINT "AUTH_ITEM_PK" PRIMARY KEY ("NAME")
);

CREATE TABLE "AUTH_ITEM_CHILD"
(	
	"PARENT" VARCHAR2(64 BYTE) not null, 
	"CHILD" VARCHAR2(64 BYTE) not null,
	CONSTRAINT "AUTH_ITEM_CHILD_PK" PRIMARY KEY ("PARENT", "CHILD"),
	CONSTRAINT "AUTH_ITEM_CHILD_FK1" FOREIGN KEY ("PARENT") REFERENCES AUTH_ITEM("NAME") ON DELETE CASCADE ENABLE,
	CONSTRAINT "AUTH_ITEM_CHILD_FK2" FOREIGN KEY ("CHILD") REFERENCES AUTH_ITEM("NAME") ON DELETE CASCADE ENABLE
);
   
CREATE TABLE "AUTH_ASSIGNMENT" 
(	
	"ITEMNAME" VARCHAR2(64 BYTE) not null, 
	"USERID" VARCHAR2(64 BYTE) not null, 
	"BIZRULE" VARCHAR2(4000 BYTE), 
	"DATA" VARCHAR2(4000 BYTE),
	CONSTRAINT "AUTH_ASSIGNMENT_PK" PRIMARY KEY ("ITEMNAME", "USERID"),
	CONSTRAINT "AUTH_ASSIGNMENT_FK1" FOREIGN KEY ("ITEMNAME") REFERENCES AUTH_ITEM("NAME") ON DELETE CASCADE ENABLE
);   
